### ISSUE TITLE
Sidechain torsions and Backbone C-Alpha Distances Error

### ISSUE THREAD

**Issue by erolic** [drorlab/pensa#42]
I am having an error when trying to calculate sidechains torsions and backbone ca distances;

Traceback (most recent call last):
  File "/pensa/scripts/compare_feature_distributions.py", line 165, in <module>
    names, ssi = workflow_torsions_ssi(args, feat_a, feat_b, data_a, data_b, tors='bb')
  File "/pensa/scripts/compare_feature_distributions.py", line 102, in workflow_torsions_ssi
    verbose=False, override_name_check=args.override_name_check)
TypeError: ssi_ensemble_analysis() got an unexpected keyword argument 'torsions'

then i am only getting the BB torsions with the strongest deviations calculated with (JSD) and (KSS), no sidechain torsions or backbone ca distances were printed.

Thanks.

**Comment by martinvoegele** [comment]
This should be fixed in the updated (and significantly changed) script. No keyword named `torsions` is used there anymore afaik.
If there is a problem with the new script, please open a new issue.
